spring:
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

management:
  context-path: /sys/monitor
  security:
    enabled: true


security:
  user:
    name: linshu
    password: linshu
  basic:
    path: /sys/monitor/**